### ISSUE TITLE
jing throws NullPointerException when attempting to resolve catalog entry

### ISSUE THREAD

**Issue by chrispitude** [relaxng/jing-trang#225]
When I run jing with a catalog file:

`jing -C ../../../../../catalog-dita.xml topic.rng
`
I get a NullPointerException as follows:

```
Exception in thread "main" java.lang.NullPointerException
        at org.apache.xml.resolver.helpers.PublicId.normalize(PublicId.java:58)
        at org.apache.xml.resolver.Catalog.resolveLocalPublic(Catalog.java:1595)
        at org.apache.xml.resolver.Catalog.resolvePublic(Catalog.java:1525)
        at com.thaiopensource.resolver.catalog.CatalogResolver.resolve(CatalogResolver.java:79)
        at com.thaiopensource.resolver.SequenceResolver.resolve(SequenceResolver.java:18)
        at com.thaiopensource.resolver.xml.sax.SAX$EntityResolverImpl.resolveEntity(SAX.java:205)
        at org.apache.xerces.util.EntityResolver2Wrapper.resolveEntity(Unknown Source)
        at org.apache.xerces.impl.XMLEntityManager.resolveEntity(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.thaiopensource.relaxng.parse.sax.SAXParseable.parse(SAXParseable.java:39)
        at com.thaiopensource.relaxng.pattern.SchemaBuilderImpl.makeExternalRef(SchemaBuilderImpl.java:717)
        at com.thaiopensource.relaxng.pattern.SchemaBuilderImpl.makeExternalRef(SchemaBuilderImpl.java:41)
        at com.thaiopensource.relaxng.parse.sax.SchemaParser$ExternalRefState.makePattern(SchemaParser.java:1114)
        at com.thaiopensource.relaxng.parse.sax.SchemaParser$EmptyContentState.end(SchemaParser.java:458)
        at com.thaiopensource.relaxng.parse.sax.SchemaParser$State.endElement(SchemaParser.java:237)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.thaiopensource.relaxng.parse.sax.SAXParseable.parseAsInclude(SAXParseable.java:55)
        at com.thaiopensource.relaxng.pattern.SchemaBuilderImpl$IncludeImpl.endInclude(SchemaBuilderImpl.java:674)
        at com.thaiopensource.relaxng.pattern.SchemaBuilderImpl$IncludeImpl.endInclude(SchemaBuilderImpl.java:622)
        at com.thaiopensource.relaxng.parse.sax.SchemaParser$IncludeState.end(SchemaParser.java:1010)
        at com.thaiopensource.relaxng.parse.sax.SchemaParser$State.endElement(SchemaParser.java:237)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.xinclude.XIncludeHandler.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.thaiopensource.validate.auto.AutoSchemaReader.createSchema(AutoSchemaReader.java:69)
        at com.thaiopensource.validate.ValidationDriver.loadSchema(ValidationDriver.java:126)
        at com.thaiopensource.relaxng.util.Driver.doMain(Driver.java:142)
        at com.thaiopensource.relaxng.util.Driver.main(Driver.java:35)
```

I tried applying the patch contained in [issue 200 (Jing is unable to process XML catalogs with multiple nextCatalog entries)](https://github.com/relaxng/jing-trang/issues/200), but it didn't fix the problem.

Testcase attached.
[testcase.zip](https://github.com/relaxng/jing-trang/files/2399048/testcase.zip)

**Comment by sideshowbarker** [comment]
Thanks for reporting this. I am planning to do a new release soon (see #231) but I unfortunately can’t make time myself to investigate and fix this issue any time soon. So if it’s important for you that a fix for this gets into the release, then we’re gonna need for somebody to make time to write up a patch.

**Comment by chrispy-snps** [comment]
Hey @sideshowbarker, it's been awhile!

I was able to narrow this down to a simple root cause. If a grammar file has a `<!DOCTYPE>` declaration:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grammar SYSTEM "./relaxng.dtd">
<grammar xmlns="http://relaxng.org/ns/structure/1.0">
  <start>
    <element name="topic"/>
  </start>
</grammar>
```

and the `jing` command line specifies a catalog file (even an empty/unused one), then the crash occurs. I think the crash is actually inside the XML resolver module, so I am not sure if `jing` can do anything to avoid the crash or not.

Simple testcase: [jing_doctype_crash.zip](https://github.com/relaxng/jing-trang/files/9478270/jing_doctype_crash.zip)

Command to reproduce: `jing -C catalog.xml topic.rng topic.dita`

This scenario occurs because the OASIS DITA v1.3 grammar instantiates the SVG grammar [here](https://github.com/dita-ot/dita-ot/tree/develop/src/main/plugins/org.oasis-open.dita.v1_3/rng/technicalContent/rng/svg), and the W3C SVG RelaxNG grammar files [here](https://www.w3.org/Graphics/SVG/1.1/rng/) have `<!DOCTYPE>` declarations in them.
